// <auto-generated />
using System;
using FlightDex.Flights.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightDex.Flights.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FlightDex.Flights.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CounterpartAirport")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CounterpartCity")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CounterpartCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartCode")
                        .HasDatabaseName("IX_Flights_CounterpartCode");

                    b.HasIndex("FlightCode")
                        .HasDatabaseName("IX_Flights_FlightCode");

                    b.HasIndex("Airport", "Direction", "ScheduledTime")
                        .HasDatabaseName("IX_Flights_Airport_Direction_Time");

                    b.ToTable("Flights", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
