// <auto-generated />
using System;
using FlightDex.Flights.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightDex.Flights.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightDex.Flights.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CounterpartAirport")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CounterpartCity")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CounterpartCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartCode")
                        .HasDatabaseName("IX_Flights_CounterpartCode");

                    b.HasIndex("FlightCode")
                        .HasDatabaseName("IX_Flights_FlightCode");

                    b.HasIndex("Airport", "Direction", "ScheduledTime")
                        .HasDatabaseName("IX_Flights_Airport_Direction_Time");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("FlightDex.Flights.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Locations_Code");

                    b.ToTable("Locations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
